@startuml

package "net/rpc/server.go" #DDDDDD {
    class rpc {
        var DefaultServer
        type methodType struct
        type service struct
        type Request struct
        type Response struct
        type Server struct
        type ServerCodec interface
        + Accept(lis net.Listener)
        + Register(rcvr interface{}) error
        + ServerConn(conn io.ReadWriteCloser)
        + ServeCodec(codec ServerCodec)
        + ServeRequest(codec ServerCodec) error
        + HandleHTTP()
    }

    class server {
        serviceMap sync.Map // 服务对象集合
    	reqLock    sync.Mutex // request 锁，保护 freeReq
    	freeReq    *Request
    	respLock   sync.Mutex // response 锁，保护 freeResp
    	freeResp   *Response
        + Register(rcvr interface{}) error
        + RegisterName(name string, rcvr interface{}) error
        + register(rcvr interface{}, name string, useName bool) error
        + sendResponse(sending *sync.Mutex, req *Request, reply interface{}, codec ServerCodec, errmsg string)
        + ServeConn(conn io.ReadWriteCloser)
        + ServeCodec(codec ServerCodec)
        + ServeRequest(codec ServerCodec) error
        + getRequest() *Request
        + freeRequest(req *Request)
        + getResponse() *Response
        + freeResponse(resp *Response)
        + readRequest(codec ServerCodec) (service *service, mtype *methodType, req *Request, argv, replyv reflect.Value, keepReading bool, err error)
        + readRequestHeader(codec ServerCodec) (svc *service, mtype *methodType, req *Request, keepReading bool, err error)
        + Accept(lis net.Listener)
        + ServeHTTP(w http.ResponseWriter, req *http.Request)
        + HandleHTTP(rpcPath, debugPath string)
    }

    class gobClientCodec {
        rwc    io.ReadWriteCloser
    	dec    *gob.Decoder
    	enc    *gob.Encoder
    	encBuf *bufio.Writer
    	closed bool
        + ReadRequestHeader(r *Request) error // 解码请求
        + ReadRequestBody(body interface{}) error
        + WriteResponse(r *Response, body interface{}) (err error) // 编码响应
        + Close() error
    }

    class service {
        name   string // 服务名
        rcvr   reflect.Value // 服务中函数的接收者
        typ    reflect.Type // 接收者类型
        method map[string]*methodType // 已注册的函数集
        + call(server *Server, sending *sync.Mutex, wg *sync.WaitGroup, mtype *methodType, req *Request, argv, replyv reflect.Value, codec ServerCodec)
    }

    gobClientCodec -up-> server: 服务端与客户端定义相同的编解码器来进行 requests 和 responses 的序列化工作
    server -up-> rpc: server.go.rpc 的导出函数基本调用 DefaultServer 的函数
    service -up-> server: server 的 ServeCodec 函数调用 service 的 call 方法来调取服务
}

@enduml
